export const GET_USER_LOCATIONS = "GET_USER_LOCATIONS";
export const GET_SELECTED_ADDRESS = "GET_SELECTED_ADDRESS";
export const GET_PUBLIC_COORDINATES = "GET_PUBLIC_COORDINATES";
export const GET_USER_COORDINATES = "GET_USER_COORDINATES";
export const GET_PUBLIC_MAP_DATA = "GET_PUBLIC_MAP_DATA";
export const GET_PRIVATE_MAP_DATA = "GET_PRIVATE_MAP_DATA";
export const GET_ALERT_DATA = "GET_ALERT_DATA";
export const SET_PUBLIC_VIEWPORT = "SET_PUBLIC_VIEWPORT";
export const SET_PRIVATE_VIEWPORT = "SET_PRIVATE_VIEWPORT";
export const SET_TRIGGER_REGISTRATION_BUTTON =
  "SET_TRIGGER_REGISTRATION_BUTTON";
export const SET_SHOW_ALERT = "SET_SHOW_ALERT";
export const SET_ALERT_VIEWED = "SET_ALERT_VIEWED";
