export const SET_LOCATION = "SET_LOCATION";
export const SET_NAME = "SET_NAME";
export const GET_FIRES_START = "GET_FIRES_START"
export const GET_FIRES_SUCCESS = "GET_FIRES_SUCCESS"
export const GET_FIRES_ERROR = "GET_FIRES_ERROR"
export const GET_USER_LOCATIONS_START = "GET_USER_LOCATIONS_START"
export const GET_USER_LOCATIONS_SUCCESS = "GET_USER_LOCATIONS_SUCCESS"
export const GET_USER_LOCATIONS_ERROR = "GET_USER_LOCATIONS_ERROR"